In [1]:
# PyTorch Tutorial: Creating and Manipulating Tensors

# Step 1: Import the necessary libraries
import torch

In [2]:
# Step 2: Creating Tensors
# Creating a tensor from a list
tensor_list = [1, 2, 3, 4, 5]
tensor = torch.tensor(tensor_list)
print("Tensor from a list:")
print(tensor)

Tensor from a list:
tensor([1, 2, 3, 4, 5])


In [13]:
# Creating a tensor from a NumPy array
import numpy as np
numpy_array = np.array([6, 7, 8, 9, 10, 11])
tensor = torch.from_numpy(numpy_array)
print("\nTensor from a NumPy array:")
print(tensor)


Tensor from a NumPy array:
tensor([ 6,  7,  8,  9, 10, 11])


In [14]:
# Creating a tensor with predefined values
tensor_zeros = torch.zeros((2, 3))
tensor_ones = torch.ones((2, 3))
tensor_rand = torch.randn((2, 3))
print("\nTensor with predefined values:")
print("Zeros:")
print(tensor_zeros)
print("Ones:")
print(tensor_ones)
print("Random:")
print(tensor_rand)


Tensor with predefined values:
Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Random:
tensor([[-1.6372,  0.5112,  1.3577],
        [-0.3202, -0.2839,  0.2749]])


In [15]:
# Step 3: Tensor Attributes and Operations
# Shape of a tensor
print("\nShape of a tensor:")
print(tensor_zeros.shape)


Shape of a tensor:
torch.Size([2, 3])


In [16]:
# Data type of a tensor
print("\nData type of a tensor:")
print(tensor_zeros.dtype)


Data type of a tensor:
torch.float32


In [33]:
# Reshaping a tensor
tensor_reshape = tensor.view(2, 3)
print("\nReshaped tensor:")
print(tensor_reshape)


Reshaped tensor:
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])


In [34]:
# Element-wise multiplication
tensor_mul = tensor_reshape * tensor_ones
print("\nElement-wise multiplication:")
print(tensor_mul)


Element-wise multiplication:
tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [47]:
# Matrix multiplication
tensor_reshape = tensor_reshape.view(3,2)
tensor_ones = tensor_ones.long()

tensor_matmul = torch.matmul(tensor_reshape, tensor_ones)
print("\nMatrix multiplication:")
print(tensor_matmul)


Matrix multiplication:
tensor([[13, 13, 13],
        [17, 17, 17],
        [21, 21, 21]])


In [46]:
tensor_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [27]:
# Step 4: Tensor to NumPy Conversion
numpy_array = tensor.numpy()
print("\nTensor to NumPy array:")
print(numpy_array)


Tensor to NumPy array:
[ 6  7  8  9 10 11]


In [28]:
# Step 5: GPU Acceleration (if available)
# Check if GPU is available
if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor = tensor.to(device)
    print("\nTensor moved to GPU:")
    print(tensor)
